### PR TITLE
#47 emailing not working

### LINKED ISSUE #47: Emailing not working
`C:\\Program Files\\mSupply Dashboard\\bin\\data\\template.xlsx: The system cannot find the path specified.`

The revert of `homePath, _ := filepath.Abs(".")` might not have been done properly 🙄

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #47 - had indeed missed one instance of the "." to ".." revert.
Offroad - committing the plugin signing change, as I had some issues with signing the plugin.

### CODE REVIEW

File: backend/pkg/reporter/reporter.go [hunk 1]
```diff
@@ -277,8 +277,7 @@ func (r *Report) Write(auth auth.AuthConfig) error {
 
 func GetFilePath(fileName string) string {
 
-	homePath, _ := filepath.Abs(".")
-	filePath := filepath.Join(homePath, "data", fileName+".xlsx")
```
Comment (joshxg) [inline backend/pkg/reporter/reporter.go:281]: Ugh - sorry I missed it!

**Review by joshxg — APPROVED** [review]

File: backend/pkg/reporter/reporter.go (hunk 1 above)
Comment (mark-prins) [reply backend/pkg/reporter/reporter.go:281]: ditto.
